# Generated by Django 5.0.6 on 2024-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manage', '0003_rename_description_product_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('website', 'Website'), ('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('myntra', 'Myntra'), ('ayuvya', 'Ayuvya')], max_length=10),
        ),
    ]
